// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyThuVien_WPF.Models;

#nullable disable

namespace QuanLyThuVien_WPF.Migrations
{
    [DbContext(typeof(qlthuvienContext))]
    [Migration("20260323183942_qltv_nhom2")]
    partial class qltv_nhom2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QuanLyThuVien_WPF.Models.ChiTietMuon", b =>
                {
                    b.Property<int>("Maphieumuon")
                        .HasColumnType("int");

                    b.Property<int>("Masachmuon")
                        .HasColumnType("int");

                    b.Property<int?>("Maphieutra")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Ngaytrathucte")
                        .HasColumnType("datetime2");

                    b.HasKey("Maphieumuon", "Masachmuon");

                    b.HasIndex("Maphieutra");

                    b.HasIndex("Masachmuon");

                    b.ToTable("ChiTietMuon", (string)null);
                });

            modelBuilder.Entity("QuanLyThuVien_WPF.Models.Docgia", b =>
                {
                    b.Property<int>("Madocgia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDocGia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Madocgia"), 1L, 1);

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Madocgia");

                    b.ToTable("DocGia", (string)null);
                });

            modelBuilder.Entity("QuanLyThuVien_WPF.Models.Loaisach", b =>
                {
                    b.Property<int>("Maloai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaLoai");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Maloai"), 1L, 1);

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tenloai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Maloai");

                    b.ToTable("LoaiSach", (string)null);
                });

            modelBuilder.Entity("QuanLyThuVien_WPF.Models.Nhanvien", b =>
                {
                    b.Property<int>("Manv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Manv"), 1L, 1);

                    b.Property<string>("Chucvu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Matkhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Taikhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Manv");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("QuanLyThuVien_WPF.Models.Nhaxuatban", b =>
                {
                    b.Property<int>("Manxb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNXB");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Manxb"), 1L, 1);

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tennxb")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Manxb");

                    b.ToTable("NhaXuatBan", (string)null);
                });

            modelBuilder.Entity("QuanLyThuVien_WPF.Models.PhieuMuon", b =>
                {
                    b.Property<int>("Maphieumuon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaPhieuMuon");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Maphieumuon"), 1L, 1);

                    b.Property<string>("Ghichu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Madocgia")
                        .HasColumnType("int");

                    b.Property<int?>("Manhanvien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Ngaymuon")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngaytra")
                        .HasColumnType("datetime2");

                    b.HasKey("Maphieumuon");

                    b.HasIndex("Madocgia");

                    b.HasIndex("Manhanvien");

                    b.ToTable("PhieuMuon", (string)null);
                });

            modelBuilder.Entity("QuanLyThuVien_WPF.Models.PhieuTra", b =>
                {
                    b.Property<int>("Maphieutra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaPhieuTra");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Maphieutra"), 1L, 1);

                    b.Property<string>("Ghichu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Manhanvien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Ngaytra")
                        .HasColumnType("datetime2");

                    b.HasKey("Maphieutra");

                    b.HasIndex("Manhanvien");

                    b.ToTable("PhieuTra", (string)null);
                });

            modelBuilder.Entity("QuanLyThuVien_WPF.Models.Sach", b =>
                {
                    b.Property<int>("Masach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaSach");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Masach"), 1L, 1);

                    b.Property<int?>("Maloai")
                        .HasColumnType("int");

                    b.Property<int?>("Manxb")
                        .HasColumnType("int");

                    b.Property<int?>("Namxb")
                        .HasColumnType("int");

                    b.Property<int?>("Soluong")
                        .HasColumnType("int");

                    b.Property<int?>("Sotrang")
                        .HasColumnType("int");

                    b.Property<string>("Tensach")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tomtat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Masach");

                    b.HasIndex("Maloai");

                    b.HasIndex("Manxb");

                    b.ToTable("Sach", (string)null);
                });

            modelBuilder.Entity("QuanLyThuVien_WPF.Models.SachMuon", b =>
                {
                    b.Property<int>("Masachmuon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaSachMuon");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Masachmuon"), 1L, 1);

                    b.Property<int?>("Masach")
                        .HasColumnType("int");

                    b.Property<string>("Tinhtrang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Masachmuon");

                    b.HasIndex("Masach");

                    b.ToTable("SachMuon", (string)null);
                });

            modelBuilder.Entity("QuanLyThuVien_WPF.Models.ChiTietMuon", b =>
                {
                    b.HasOne("QuanLyThuVien_WPF.Models.PhieuMuon", "MaphieumuonNavigation")
                        .WithMany("ChiTietMuons")
                        .HasForeignKey("Maphieumuon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CT_PhieuMuon");

                    b.HasOne("QuanLyThuVien_WPF.Models.PhieuTra", "MaphieutraNavigation")
                        .WithMany("ChiTietMuons")
                        .HasForeignKey("Maphieutra")
                        .HasConstraintName("FK_CT_PhieuTra");

                    b.HasOne("QuanLyThuVien_WPF.Models.SachMuon", "MasachmuonNavigation")
                        .WithMany("ChiTietMuons")
                        .HasForeignKey("Masachmuon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CT_SachMuon");

                    b.Navigation("MaphieumuonNavigation");

                    b.Navigation("MaphieutraNavigation");

                    b.Navigation("MasachmuonNavigation");
                });

            modelBuilder.Entity("QuanLyThuVien_WPF.Models.PhieuMuon", b =>
                {
                    b.HasOne("QuanLyThuVien_WPF.Models.Docgia", "MadocgiaNavigation")
                        .WithMany("PhieuMuons")
                        .HasForeignKey("Madocgia")
                        .HasConstraintName("FK_PhieuMuon_DocGia");

                    b.HasOne("QuanLyThuVien_WPF.Models.Nhanvien", "ManhanvienNavigation")
                        .WithMany("PhieuMuons")
                        .HasForeignKey("Manhanvien")
                        .HasConstraintName("FK_PhieuMuon_NhanVien");

                    b.Navigation("MadocgiaNavigation");

                    b.Navigation("ManhanvienNavigation");
                });

            modelBuilder.Entity("QuanLyThuVien_WPF.Models.PhieuTra", b =>
                {
                    b.HasOne("QuanLyThuVien_WPF.Models.Nhanvien", "ManhanvienNavigation")
                        .WithMany("PhieuTras")
                        .HasForeignKey("Manhanvien")
                        .HasConstraintName("FK_PhieuTra_NhanVien");

                    b.Navigation("ManhanvienNavigation");
                });

            modelBuilder.Entity("QuanLyThuVien_WPF.Models.Sach", b =>
                {
                    b.HasOne("QuanLyThuVien_WPF.Models.Loaisach", "MaloaiNavigation")
                        .WithMany("Saches")
                        .HasForeignKey("Maloai")
                        .HasConstraintName("FK_Sach_LoaiSach");

                    b.HasOne("QuanLyThuVien_WPF.Models.Nhaxuatban", "ManxbNavigation")
                        .WithMany("Saches")
                        .HasForeignKey("Manxb")
                        .HasConstraintName("FK_Sach_NhaXuatBan");

                    b.Navigation("MaloaiNavigation");

                    b.Navigation("ManxbNavigation");
                });

            modelBuilder.Entity("QuanLyThuVien_WPF.Models.SachMuon", b =>
                {
                    b.HasOne("QuanLyThuVien_WPF.Models.Sach", "MasachNavigation")
                        .WithMany("SachMuons")
                        .HasForeignKey("Masach")
                        .HasConstraintName("FK_SachMuon_Sach");

                    b.Navigation("MasachNavigation");
                });

            modelBuilder.Entity("QuanLyThuVien_WPF.Models.Docgia", b =>
                {
                    b.Navigation("PhieuMuons");
                });

            modelBuilder.Entity("QuanLyThuVien_WPF.Models.Loaisach", b =>
                {
                    b.Navigation("Saches");
                });

            modelBuilder.Entity("QuanLyThuVien_WPF.Models.Nhanvien", b =>
                {
                    b.Navigation("PhieuMuons");

                    b.Navigation("PhieuTras");
                });

            modelBuilder.Entity("QuanLyThuVien_WPF.Models.Nhaxuatban", b =>
                {
                    b.Navigation("Saches");
                });

            modelBuilder.Entity("QuanLyThuVien_WPF.Models.PhieuMuon", b =>
                {
                    b.Navigation("ChiTietMuons");
                });

            modelBuilder.Entity("QuanLyThuVien_WPF.Models.PhieuTra", b =>
                {
                    b.Navigation("ChiTietMuons");
                });

            modelBuilder.Entity("QuanLyThuVien_WPF.Models.Sach", b =>
                {
                    b.Navigation("SachMuons");
                });

            modelBuilder.Entity("QuanLyThuVien_WPF.Models.SachMuon", b =>
                {
                    b.Navigation("ChiTietMuons");
                });
#pragma warning restore 612, 618
        }
    }
}
