// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLTV_WPF.Models;

#nullable disable

namespace QLTV_WPF.Migrations
{
    [DbContext(typeof(QuanLyThuVienContext))]
    [Migration("20260328132210_QLTV")]
    partial class QLTV
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QLTV_WPF.Models.ChiTietMuon", b =>
                {
                    b.Property<int>("MaPhieuMuon")
                        .HasColumnType("int");

                    b.Property<int>("MaSachMuon")
                        .HasColumnType("int");

                    b.Property<string>("LyDoPhat")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaPhieuTra")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTraThucTe")
                        .HasColumnType("date");

                    b.Property<decimal?>("TienPhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("MaPhieuMuon", "MaSachMuon")
                        .HasName("PK__ChiTietM__5152017268A420CE");

                    b.HasIndex("MaPhieuTra");

                    b.HasIndex("MaSachMuon");

                    b.ToTable("ChiTietMuon", (string)null);
                });

            modelBuilder.Entity("QLTV_WPF.Models.DocGium", b =>
                {
                    b.Property<int>("MaDocGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDocGia"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SDT");

                    b.HasKey("MaDocGia")
                        .HasName("PK__DocGia__F165F945F812173C");

                    b.ToTable("DocGia");
                });

            modelBuilder.Entity("QLTV_WPF.Models.LoaiSach", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"), 1L, 1);

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoai")
                        .HasName("PK__LoaiSach__730A5759901A478D");

                    b.ToTable("LoaiSach", (string)null);
                });

            modelBuilder.Entity("QLTV_WPF.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNv"), 1L, 1);

                    b.Property<string>("ChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SDT");

                    b.Property<string>("TaiKhoan")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaNv")
                        .HasName("PK__NhanVien__2725D70A9CF9D9D5");

                    b.HasIndex(new[] { "TaiKhoan" }, "UQ__NhanVien__D5B8C7F0B10D9FAE")
                        .IsUnique()
                        .HasFilter("[TaiKhoan] IS NOT NULL");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("QLTV_WPF.Models.NhaXuatBan", b =>
                {
                    b.Property<int>("MaNxb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNXB");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNxb"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenNxb")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("TenNXB");

                    b.HasKey("MaNxb")
                        .HasName("PK__NhaXuatB__3A19482CAE502F4B");

                    b.ToTable("NhaXuatBan", (string)null);
                });

            modelBuilder.Entity("QLTV_WPF.Models.PhieuMuon", b =>
                {
                    b.Property<int>("MaPhieuMuon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuMuon"), 1L, 1);

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaDocGia")
                        .HasColumnType("int");

                    b.Property<int?>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayMuon")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayTra")
                        .HasColumnType("date");

                    b.HasKey("MaPhieuMuon")
                        .HasName("PK__PhieuMuo__C4C82222E6645F44");

                    b.HasIndex("MaDocGia");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("PhieuMuon", (string)null);
                });

            modelBuilder.Entity("QLTV_WPF.Models.PhieuTra", b =>
                {
                    b.Property<int>("MaPhieuTra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuTra"), 1L, 1);

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTra")
                        .HasColumnType("date");

                    b.Property<decimal?>("TongTienPhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("MaPhieuTra")
                        .HasName("PK__PhieuTra__1D880A463EE4B7AD");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("PhieuTra", (string)null);
                });

            modelBuilder.Entity("QLTV_WPF.Models.Sach", b =>
                {
                    b.Property<int>("MaSach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSach"), 1L, 1);

                    b.Property<int?>("MaLoai")
                        .HasColumnType("int");

                    b.Property<int?>("MaNxb")
                        .HasColumnType("int")
                        .HasColumnName("MaNXB");

                    b.Property<int?>("NamXb")
                        .HasColumnType("int")
                        .HasColumnName("NamXB");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int?>("SoTrang")
                        .HasColumnType("int");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TomTat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSach")
                        .HasName("PK__Sach__B235742D12AD972D");

                    b.HasIndex("MaLoai");

                    b.HasIndex("MaNxb");

                    b.ToTable("Sach", (string)null);
                });

            modelBuilder.Entity("QLTV_WPF.Models.SachMuon", b =>
                {
                    b.Property<int>("MaSachMuon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSachMuon"), 1L, 1);

                    b.Property<int?>("MaSach")
                        .HasColumnType("int");

                    b.Property<string>("TinhTrang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaSachMuon")
                        .HasName("PK__SachMuon__59A235086C6C957D");

                    b.HasIndex("MaSach");

                    b.ToTable("SachMuon", (string)null);
                });

            modelBuilder.Entity("QLTV_WPF.Models.TacGium", b =>
                {
                    b.Property<int>("MaTg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTG");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTg"), 1L, 1);

                    b.Property<string>("TenTg")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenTG");

                    b.Property<string>("TieuSu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTg")
                        .HasName("PK__TacGia__27250074E9A0C9AC");

                    b.ToTable("TacGia");
                });

            modelBuilder.Entity("SachTacGium", b =>
                {
                    b.Property<int>("MaSach")
                        .HasColumnType("int");

                    b.Property<int>("MaTg")
                        .HasColumnType("int")
                        .HasColumnName("MaTG");

                    b.HasKey("MaSach", "MaTg")
                        .HasName("PK__Sach_Tac__E047242AC5D92F86");

                    b.HasIndex("MaTg");

                    b.ToTable("Sach_TacGia", (string)null);
                });

            modelBuilder.Entity("QLTV_WPF.Models.ChiTietMuon", b =>
                {
                    b.HasOne("QLTV_WPF.Models.PhieuMuon", "MaPhieuMuonNavigation")
                        .WithMany("ChiTietMuons")
                        .HasForeignKey("MaPhieuMuon")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietMu__MaPhi__5165187F");

                    b.HasOne("QLTV_WPF.Models.PhieuTra", "MaPhieuTraNavigation")
                        .WithMany("ChiTietMuons")
                        .HasForeignKey("MaPhieuTra")
                        .HasConstraintName("FK__ChiTietMu__MaPhi__534D60F1");

                    b.HasOne("QLTV_WPF.Models.SachMuon", "MaSachMuonNavigation")
                        .WithMany("ChiTietMuons")
                        .HasForeignKey("MaSachMuon")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietMu__MaSac__52593CB8");

                    b.Navigation("MaPhieuMuonNavigation");

                    b.Navigation("MaPhieuTraNavigation");

                    b.Navigation("MaSachMuonNavigation");
                });

            modelBuilder.Entity("QLTV_WPF.Models.PhieuMuon", b =>
                {
                    b.HasOne("QLTV_WPF.Models.DocGium", "MaDocGiaNavigation")
                        .WithMany("PhieuMuons")
                        .HasForeignKey("MaDocGia")
                        .HasConstraintName("FK__PhieuMuon__MaDoc__48CFD27E");

                    b.HasOne("QLTV_WPF.Models.NhanVien", "MaNhanVienNavigation")
                        .WithMany("PhieuMuons")
                        .HasForeignKey("MaNhanVien")
                        .HasConstraintName("FK__PhieuMuon__MaNha__49C3F6B7");

                    b.Navigation("MaDocGiaNavigation");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("QLTV_WPF.Models.PhieuTra", b =>
                {
                    b.HasOne("QLTV_WPF.Models.NhanVien", "MaNhanVienNavigation")
                        .WithMany("PhieuTras")
                        .HasForeignKey("MaNhanVien")
                        .HasConstraintName("FK__PhieuTra__MaNhan__4D94879B");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("QLTV_WPF.Models.Sach", b =>
                {
                    b.HasOne("QLTV_WPF.Models.LoaiSach", "MaLoaiNavigation")
                        .WithMany("Saches")
                        .HasForeignKey("MaLoai")
                        .HasConstraintName("FK__Sach__MaLoai__4222D4EF");

                    b.HasOne("QLTV_WPF.Models.NhaXuatBan", "MaNxbNavigation")
                        .WithMany("Saches")
                        .HasForeignKey("MaNxb")
                        .HasConstraintName("FK__Sach__MaNXB__4316F928");

                    b.Navigation("MaLoaiNavigation");

                    b.Navigation("MaNxbNavigation");
                });

            modelBuilder.Entity("QLTV_WPF.Models.SachMuon", b =>
                {
                    b.HasOne("QLTV_WPF.Models.Sach", "MaSachNavigation")
                        .WithMany("SachMuons")
                        .HasForeignKey("MaSach")
                        .HasConstraintName("FK__SachMuon__MaSach__45F365D3");

                    b.Navigation("MaSachNavigation");
                });

            modelBuilder.Entity("SachTacGium", b =>
                {
                    b.HasOne("QLTV_WPF.Models.Sach", null)
                        .WithMany()
                        .HasForeignKey("MaSach")
                        .IsRequired()
                        .HasConstraintName("FK__Sach_TacG__MaSac__5629CD9C");

                    b.HasOne("QLTV_WPF.Models.TacGium", null)
                        .WithMany()
                        .HasForeignKey("MaTg")
                        .IsRequired()
                        .HasConstraintName("FK__Sach_TacGi__MaTG__571DF1D5");
                });

            modelBuilder.Entity("QLTV_WPF.Models.DocGium", b =>
                {
                    b.Navigation("PhieuMuons");
                });

            modelBuilder.Entity("QLTV_WPF.Models.LoaiSach", b =>
                {
                    b.Navigation("Saches");
                });

            modelBuilder.Entity("QLTV_WPF.Models.NhanVien", b =>
                {
                    b.Navigation("PhieuMuons");

                    b.Navigation("PhieuTras");
                });

            modelBuilder.Entity("QLTV_WPF.Models.NhaXuatBan", b =>
                {
                    b.Navigation("Saches");
                });

            modelBuilder.Entity("QLTV_WPF.Models.PhieuMuon", b =>
                {
                    b.Navigation("ChiTietMuons");
                });

            modelBuilder.Entity("QLTV_WPF.Models.PhieuTra", b =>
                {
                    b.Navigation("ChiTietMuons");
                });

            modelBuilder.Entity("QLTV_WPF.Models.Sach", b =>
                {
                    b.Navigation("SachMuons");
                });

            modelBuilder.Entity("QLTV_WPF.Models.SachMuon", b =>
                {
                    b.Navigation("ChiTietMuons");
                });
#pragma warning restore 612, 618
        }
    }
}
